export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const VALIDATE_ERROR = 'VALIDATE_ERROR'
export const INFO = 'INFO'
export const LOAD_WORKFLOW = 'LOAD_WORKFLOW'
export const LOAD_FIGURE_STATUS = 'LOAD_FIGURE_STATUS'
