export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const VALIDATE_ERROR = 'VALIDATE_ERROR'
export const INFO = 'INFO'

export const ADD_OPERATOR = 'ADD_OPERATOR'
export const EDIT_OPERATOR = 'EDIT_OPERATOR'
export const GET_OPERATOR = 'GET_OPERATOR'
export const DELETE_OPERATOR = 'DELETE_OPERATOR'
export const LIST_OPERATORS = 'LIST_OPERATORS'

export const ADD_HOUSEHOLDER = 'ADD_HOUSEHOLDER'
export const EDIT_HOUSEHOLDER = 'EDIT_HOUSEHOLDER'
export const GET_HOUSEHOLDER = 'GET_HOUSEHOLDER'
export const DELETE_HOUSEHOLDER = 'DELETE_HOUSEHOLDER'
export const LIST_HOUSEHOLDERS = 'LIST_HOUSEHOLDERS'
export const KEEP_HOUSEHOLDERID = 'KEEP_HOUSEHOLDERID'


export const ADD_HOUSE = 'ADD_HOUSE'
export const EDIT_HOUSE = 'EDIT_HOUSE'
export const GET_HOUSE = 'GET_HOUSE'
export const DELETE_HOUSE = 'DELETE_HOUSE'
export const LIST_HOUSES = 'LIST_HOUSES'
export const KEEP_HOUSEID = 'KEEP_HOUSEID'

export const ADD_EQUIPMENT = 'ADD_EQUIPMENT'
export const UNBIND_EQUIPMENT = 'UNBIND_EQUIPMENT'
export const EDIT_EQUIPMENT = 'EDIT_EQUIPMENT'
export const GET_EQUIPMENT = 'GET_EQUIPMENT'
export const LIST_EQUIPMENT = 'LIST_EQUIPMENT'

export const LOAD_WORKFLOW = 'LOAD_WORKFLOW'
export const LOAD_FIGURE_STATUS = 'LOAD_FIGURE_STATUS'
export const SHOW_PORTS = 'SHOW_PORTS'
export const SHOW_GRID = 'SHOW_GRID'

